[project]
name = "benchmark"
version = "0.1.0"
description = "Add a short description here"
authors = ["Claudius Kienle <claudius.kienle@artiminds.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
numpy = ">=2.1.1,<2.2"
pandas = ">=2.2.2,<2.3"
ipykernel = ">=6.29.5,<6.30"
jinja2 = ">=3.1.4,<3.2"
